server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE:http://localhost:8761/eureka/}
    instance:
      prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resources/**
          filters:
            - name: CircuitBreaker
              args:
                name: resourceServiceCircuitBreaker
                fallbackUri: forward:/fallback/resources
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songs/**
          filters:
            - name: CircuitBreaker
              args:
                name: songServiceCircuitBreaker
                fallbackUri: forward:/fallback/songs
        # Catch-all route for undefined endpoints
        - id: fallback-route
          uri: forward:/fallback
          predicates:
            - Path=/**
