server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE:http://localhost:8761/eureka/}
    registryFetchIntervalSeconds: 30
    heartbeatExecutorThreadPoolSize: 5
    initialInstanceInfoReplicationIntervalSeconds: 40

spring:
  application:
    name: resource-processor

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}

  cloud:
    function:
      definition: createResourceMetadata
    stream:
      bindings:
        createResourceMetadata-in-0:
          destination: ${APP_RABBITMQ_RESOURCE_EXCHANGE:resource.exchange}
          group: ${APP_RABBITMQ_RESOURCE_GROUP:createResource}
          content-type: text/plain

        processSongMetadata-out-0:
          destination: ${APP_RABBITMQ_METADATA_EXCHANGE:metadata.exchange}
          content-type: text/plain
      rabbit:
        bindings:
          createResourceMetadata-in-0:
            consumer:
              acknowledge-mode: AUTO
              auto-bind-dlq: true # automatically create DLQ
              republish-to-dlq: true       # send message to DLQ after retries
              default-requeue-rejected: false
              default-retryable: true      # enable retries for exceptions
              max-attempts: 3              # number of retry attempts
              back-off-initial-interval: 2000 # 2 seconds
              back-off-max-interval: 10000    # 10 seconds
              back-off-multiplier: 2.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    enabled: true           # enables metrics endpoint
    prometheus:
      enabled: true
    tags:
      application: ${spring.application.name}
song:
  service:
    url: ${SONG_SERVICE_URL:http://song-service:8081}
resource:
  service:
    url: ${RESOURCE_SERVICE_URL:http://resource-service:8085}

#logstash:
#  host: ${LOGSTASH_HOST:logstash}
#  port: ${LOGSTASH_PORT:5000}
#  queue-size: 512