server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE:http://localhost:8761/eureka/}

spring:
  application:
    name: resource-processor

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}

  cloud:
    function:
      definition: createResourceMetadata;auditDeleteResourceMetadata
    stream:
      bindings:
        createResourceMetadata-in-0:
          destination: ${APP_RABBITMQ_EXCHANGE:resource.exchange}
          group: ${APP_RABBITMQ_GROUP:createMetadata}
          content-type: text/plain
      rabbit:
        bindings:
          createResourceMetadata-in-0:
            consumer:
              acknowledge-mode: AUTO
              auto-bind-dlq: true # automatically create DLQ
              republish-to-dlq: true       # send message to DLQ after retries
              default-requeue-rejected: false
              default-retryable: true      # enable retries for exceptions
              max-attempts: 3              # number of retry attempts
              back-off-initial-interval: 2000 # 2 seconds
              back-off-max-interval: 10000    # 10 seconds
              back-off-multiplier: 2.0
song:
  service:
    url: ${SONG_SERVICE_URL:http://song-service:8081}
resource:
  service:
    url: ${RESOURCE_SERVICE_URL:http://resource-service:8085}