server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE:http://localhost:8761/eureka/}

spring:
  application:
    name: resource-processor

song:
  service:
    url: ${SONG_SERVICE_URL:http://song-service:8081}

s3:
  endpoint: ${S3_ENDPOINT:http://localhost:4566}
  access-key: ${S3_ACCESS_KEY:test}
  secret-key: ${S3_SECRET_KEY:test}
  bucket: ${S3_BUCKET:resource-files}
  region: ${S3_REGION:us-east-1}