server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    enabled: true           # enables metrics endpoint
    prometheus:
      enabled: true
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: song-service
  cloud:
    config:
      name: song-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/SONG_DB}
    username: ${POSTGRES_USER:myuser}
    password: ${POSTGRES_PASSWORD:mypass}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE:http://localhost:8761/eureka/}
    registryFetchIntervalSeconds: 30
    heartbeatExecutorThreadPoolSize: 5
    initialInstanceInfoReplicationIntervalSeconds: 40

#logstash:
#  host: ${LOGSTASH_HOST:logstash}
#  port: ${LOGSTASH_PORT:5000}
#  queue-size: 512