package com.example.resourceservice.cucumber.hooks;

import com.example.resourceservice.repository.ResourceRepository;
import io.cucumber.java.Before;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Import;
import org.springframework.transaction.annotation.Transactional;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

@Import(TestDatasourceConfig.class)
public class DatabaseHooks {

    @Autowired
    private DataSource dataSource;

    @Autowired
    private ResourceRepository resourceRepository;

    @Before
    @Transactional
    public void setupDatabase() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS resource");
            stmt.execute("DROP SEQUENCE IF EXISTS RESOURCE_SEQ");

            stmt.execute("CREATE SEQUENCE RESOURCE_SEQ START WITH 1");
            stmt.execute("""
                    CREATE TABLE resource (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        file_name VARCHAR(255),
                        s3_key VARCHAR(255),
                        uploaded_at TIMESTAMP
                    )
                    """);
        }
        resourceRepository.deleteAll();
    }
}
