server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE:http://localhost:8761/eureka/}

spring:
  application:
    name: resource-service

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}

  cloud:
    stream:
      bindings:
        createResourceMetadata-out-0:
          destination: ${APP_RABBITMQ_EXCHANGE:resource.exchange}
          content-type: text/plain
        auditDeleteResourceMetadata-out-0:
          destination: ${APP_RABBITMQ_EXCHANGE:resource.exchange}
          content-type: text/plain

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/RESOURCE_DB}
    username: ${POSTGRES_USER:myuser}
    password: ${POSTGRES_PASSWORD:mypass}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

song:
  service:
    url: ${SONG_SERVICE_URL:http://song-service:8081}

s3:
  endpoint: ${S3_ENDPOINT:http://localhost:4566}
  access-key: ${S3_ACCESS_KEY:test}
  secret-key: ${S3_SECRET_KEY:test}
  bucket: ${S3_BUCKET:resource-files}
  region: ${S3_REGION:us-east-1}